services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clinic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/ahmedabdallah2532004-wq/clinic-system-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/clinic_db?schema=public
      - PORT=3001
      - JWT_SECRET=supersecretjwtkey123
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    image: ghcr.io/ahmedabdallah2532004-wq/clinic-system-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001

volumes:
  postgres_data:
